segmentation:
  ros__parameters:
    max_avg_distance_from_sensor: 1.5
    min_avg_distance_from_sensor: 0.0
    max_points_segment: 100
    min_points_segment: 3
    max_segment_width: 0.2
    min_segment_width: 0.04
    method_threshold: santos # lee santos ''
    distance_threshold: 0.05
    noise_reduction: 0.3
    scan_topic: scan_feet
    segmentation_type: jump_distance_merge
    segments_topic: segments
