<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="walker">


    <!--All units in m-kg-s-radians unit system -->
    <xacro:arg name="wheel_diameter_prop" default="0.15"/>
    <xacro:arg name="wheel_section_prop" default="0.022"/>
    <xacro:arg name="wheel_separation_prop" default="0.575"/>
    <xacro:arg name="back_front_wheel_separation_prop" default="0.53"/>
    <!-- In base_footprint coordinates: 
          0,0,0 is at floor level in the middle point between back wheels
          x+ is towards front wheels
          y+ is right side
          z+ is up          
    -->
    <xacro:arg name="lidar_pos_x_prop" default="0.55"/>
    <xacro:arg name="lidar_pos_y_prop" default="0.0"/>
    <xacro:arg name="lidar_pos_z_prop" default="0.21"/>
    <xacro:arg name="witmotion_pos_x_prop" default="0.565"/>
    <xacro:arg name="witmotion_pos_y_prop" default="0.0"/>
    <xacro:arg name="witmotion_pos_z_prop" default="0.305"/>
    <xacro:arg name="witmotion_size_x_prop" default="0.0513"/>
    <xacro:arg name="witmotion_size_y_prop" default="0.036"/>
    <xacro:arg name="witmotion_size_z_prop" default="0.015"/>    
    <!-- Handle links are managed by handle_tf_publisher.py -->
    <!-- leapmotion link should be calculated elsewhere -->


    <!--Constants and operable values -->
    <xacro:property name="wheel_diameter" value="$(arg wheel_diameter_prop)" />
    <xacro:property name="wheel_section" value="$(arg wheel_section_prop)" />
    <xacro:property name="wheel_separation" value="$(arg wheel_separation_prop)" />
    <xacro:property name="back_front_wheel_separation" value="$(arg back_front_wheel_separation_prop)" />
    
    <xacro:property name="lidar_pos_x" value="$(arg lidar_pos_x_prop)" />
    <xacro:property name="lidar_pos_y" value="$(arg lidar_pos_y_prop)" />
    <xacro:property name="lidar_pos_z" value="$(arg lidar_pos_z_prop)" />
    
    <xacro:property name="witmotion_pos_x" value="$(arg witmotion_pos_x_prop)" />
    <xacro:property name="witmotion_pos_y" value="$(arg witmotion_pos_y_prop)" />
    <xacro:property name="witmotion_pos_z" value="$(arg witmotion_pos_z_prop)" />
    <xacro:property name="witmotion_size_x" value="$(arg witmotion_size_x_prop)" />
    <xacro:property name="witmotion_size_y" value="$(arg witmotion_size_y_prop)" />
    <xacro:property name="witmotion_size_z" value="$(arg witmotion_size_z_prop)" />

    <xacro:property name="model_scale_x" value="0.009" /> <!--long -->
    <xacro:property name="model_scale_y" value="0.0105" /> <!--wide -->
    <xacro:property name="model_scale_z" value="0.0075" /> <!--high -->

    <xacro:property name="M_PI" value="3.1415926535897931" />
    <xacro:property name="M_PI_2" value="1.570796327" />

    <!-- macros  --> 
    <xacro:macro name="wheel" params="name origin_xyz">">
        <link name="wheel_${name}">
            <inertial>
              <mass value="0.2"/>
              <origin rpy="0 ${M_PI_2} ${M_PI_2}" xyz="0 0 0"/>
              <inertia ixx="0.000526666666667" ixy="0" ixz="0" iyy="0.000526666666667" iyz="0" izz="0.001"/>
            </inertial>

            <collision name="wheel_${name}_collision">
              <origin rpy="0 ${M_PI_2} ${M_PI_2}" xyz="0 0 0"/>
              <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_section}"/>
              </geometry>
            </collision>
            
            <visual name="wheel_${name}_visual">
              <origin rpy="0 ${M_PI_2} ${M_PI_2}" xyz="0 0 0"/>
              <geometry>
                <cylinder radius="${wheel_diameter/2}" length="${wheel_section}"/>
              </geometry>
              <material name="black">
                <color rgba="0.0 0.0 0.0 1.0"/>
              </material>
            </visual>
        </link>


        <!-- continuous type does not get done-->
        <joint name="wheel_${name}_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${origin_xyz}"/>
            <child link="wheel_${name}"/>
            <parent link="base_footprint"/>
            <axis rpy="0 0 0" xyz="0 1 0"/>
            <limit effort="10000" velocity="1000"/>
            <joint_properties damping="1.0" friction="1.0"/>
        </joint>
    </xacro:macro> 

    <!-- root link --> 
    <link name="base_footprint"/>

    <!-- Chassis link -->
    <link name="base_link">
          <inertial>
              <mass value="8"/>
              <origin rpy="0 0 0" xyz="0 -0.1 -0.1"/>
              <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
          </inertial>

          <collision name="base_collision"> 
              <origin rpy="0 0 0" xyz="${back_front_wheel_separation} 0.0 -${wheel_diameter/2}"/>
              <geometry>                  
                  <mesh scale="${model_scale_x} ${model_scale_y} ${model_scale_z}" filename="package://walker_description/models/walker/walker_no_wheels.dae"/>        
              </geometry>
          </collision>

          <visual name="base_visual"> 
              <origin rpy="0 0 0" xyz="${back_front_wheel_separation} 0.0 -${wheel_diameter/2}"/>
              <geometry>                  
                  <mesh scale="${model_scale_x} ${model_scale_y} ${model_scale_z}" filename="package://walker_description/models/walker/walker.dae"/>        
              </geometry>
          </visual>
    </link>
     
    <joint name="base_joint" type="fixed">
      <origin xyz="0 0 ${wheel_diameter/2}" rpy="0 0 0"/>
      <parent link="base_footprint"/>
      <child link="base_link"/>
    </joint>

    <!-- Wheel links -->
    <xacro:wheel name="right" origin_xyz="0 -${wheel_separation/2} ${wheel_diameter/2}" />
    <xacro:wheel name="left"  origin_xyz="0 ${wheel_separation/2} ${wheel_diameter/2}" />

    <!-- LIDAR link --> 
    <link name="laser">
          <inertial>
              <mass value="0.004" />
              <inertia ixx="0.001" ixy="0.000" ixz="0.000" iyy="0.001" iyz="0.000" izz="0.001" />
          </inertial>

          <collision name="lidar_sensor_collision">
              <geometry>
                  <cylinder radius="0.0508" length="0.055"/>
              </geometry>
          </collision>             

          <visual name="lidar_sensor_visual">
              <geometry>
                  <mesh scale="0.001 0.001 0.001" filename="package://walker_description/models/turtlebot3_burger/meshes/lds.dae"/>                                                    
              </geometry>
              <material name="grey">
                <color rgba="0.2 0.2 0.2 1.0"/>
              </material>
          </visual>

    </link>

    <joint name="lidar_joint" type="fixed">
      <origin xyz="${lidar_pos_x} ${lidar_pos_y} ${lidar_pos_z}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/> 
      <parent link="base_footprint"/>
      <child link="laser"/>
    </joint>

    <!-- IMU link --> 
    <link name="witmotion">
          <inertial>
              <mass value="0.004" />
              <inertia ixx="0.001" ixy="0.000" ixz="0.000" iyy="0.001" iyz="0.000" izz="0.001" />
          </inertial>

          <collision name="witmotion_sensor_collision">
              <geometry>
                  <box size="${witmotion_size_x} ${witmotion_size_y} ${witmotion_size_z}"/>
              </geometry>
          </collision>             

          <visual name="witmotion_sensor_visual">
              <geometry>
                  <box size="${witmotion_size_x} ${witmotion_size_y} ${witmotion_size_z}"/>
              </geometry>
              <material name="grey">
                <color rgba="0.2 0.2 0.2 1.0"/>
              </material>
          </visual>

    </link>

    <joint name="witmotion_joint" type="fixed">
      <origin xyz="${witmotion_pos_x+witmotion_size_x/2} ${witmotion_pos_y+witmotion_size_y/2} ${witmotion_pos_z+witmotion_size_z/2}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/> 
      <parent link="base_footprint"/>
      <child link="witmotion"/>
    </joint>
    <!-- gazebo stuff 
    <xacro:include filename="package://walker_description/urdf/walker_model.gazebo" />
    --> 
</robot>
