/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 20.0
      io_method: "mmap"
      frame_id: "est_camera/left"
      pixel_format: "yuyv"  # see usb_cam/supported_formats for list of supported formats
      image_width: 800
      image_height: 600
      camera_name: "est_camera/left"
      camera_info_url: "package://walker_usb_cameras/config/est_left_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1