scan_to_scan_filter_chain:
  ros__parameters:
    use_sim_time: False
    filter1:
      name: mask
      type: laser_filters/LaserScanMaskFilter
      params:
        masks:
          laser:
          - 0.
          - 1.
          - 2.
          - 3.
          - 4.
          - 5.
          - 6.
          - 7.
          - 8.
          - 9.
          - 10.
          - 11.
          - 12.
          - 13.
          - 14.
          - 15.
          - 16.
          - 17.
          - 18.
          - 19.
          - 20.
          - 21.
          - 22.
          - 23.
          - 24.
#
          - 44.
          - 45.
          - 46.
          - 47.
          - 48.
          - 49.
          - 50.
          - 51.
          - 52.
#          
          - 174.
          - 175.
          - 176.
          - 177.
          - 178.
          - 179.
          - 180.
          - 181.
          - 182.
#          
          - 526.
          - 527.
          - 528.
          - 529.
          - 530.
          - 531.
          - 532.
          - 533.
          - 534.
          - 535.
#          
          - 656.
          - 657.
          - 658.
          - 659.
          - 660.
          - 661.
          - 662.
#          
          - 685.
          - 686.
          - 687.          
          - 688.
          - 689.
          - 690.
          - 691.
          - 692.
          - 693.
          - 694.
          - 695.
          - 696.
          - 697.
          - 698.
          - 699.
          - 700.
          - 701.
          - 702.
          - 703.
          - 704.
          - 705.
          - 706.
          - 707.
          - 708.
          - 709.
          - 710.
          - 711.
          - 712.
          - 713.
          - 714.
          - 715.
          - 716.
          - 717.
          - 718.
          - 719.