/**:
    ros__parameters:
      video_device: "/dev/video5"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg"
      image_width: 1920
      image_height: 1080   
      camera_name: "test_camera"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
