session: walker_ros2
init_cmd: |
  # Any initial config/command goes here:
  source ~/workspace/walker_ws/install/setup.bash & source ~/workspace/walker_ws/install/setup.sh
windows:
  - name: arduino
    tags: ['core']
    panes:
      - ros2 launch walker_arduino left_handle.launch.py
      - ros2 launch walker_arduino right_handle.launch.py
      - ros2 launch walker_arduino left_wheel.launch.py
      - ros2 launch walker_arduino right_wheel.launch.py
  - name: sensors1
    tags: ['core']
    panes:
      - ros2 launch rplidar_ros2  rplidar_launch.py inverted:=true
      - ros2 run bwt901cl_pkg imu_bwt901cl      
      - ros2 launch walker_diff_odom walker_diff_odom.launch.py
  - name: sensors2
    tags: ['core']
    panes:
      - ros2 launch walker_bringup laser_filter.launch.py
      - ros2 launch ros2_laser_scan_matcher demo_lsm.launch.py
      - ros2 launch leap_motion camera.launch.py
  - name: crappy_description1
    tags: ['core']
    panes:
      - ros2 run tf2_ros static_transform_publisher 0.55  0     0.210 0    0    0    base_footprint laser  # z is lower...
      - ros2 run tf2_ros static_transform_publisher 0.55  0     0.474 0    0    0    base_footprint witmotion
      - ros2 run tf2_ros static_transform_publisher 0.31  0.24  0.850 0    0    0    base_footprint left_handle_id
      - ros2 run tf2_ros static_transform_publisher 0.31 -0.24  0.850 0    0    0    base_footprint right_handle_id
      - ros2 run tf2_ros static_transform_publisher 0     0     0.075 0    0    0    base_footprint base_link 
  - name: crappy_description2
    tags: ['core']
    panes:
      - ros2 run tf2_ros static_transform_publisher 0.22  0.080 0.450  1.9  3.14  -0.55 base_footprint leap_camera_left
      - ros2 run tf2_ros static_transform_publisher 0.31 -0.080 0.450  1.9  3.14  -0.55 base_footprint leap_camera_right
      - ros2 run tf2_ros static_transform_publisher 0     0.276 0.075 0    0    0    base_footprint left_wheel_id
      - ros2 run tf2_ros static_transform_publisher 0    -0.276 0.075 0    0    3.14 base_footprint right_wheel_id
  - name: web
    tags: ['core']
    panes:
      - ros2 run walker_bringup record_service.py
      - ros2 launch rosbridge_server rosbridge_websocket_launch.xml
      - cd ~/workspace/walker_ws/src/WalKit/walker_web_gui/gui; python3 -m http.server
  - name: gait_analysis
    tags: ['core']
    panes:
      - ros2 launch walker_step_detector step_detector.launch.py
      - ros2 run walker_loads partial_loads      # should add params and launch file ...
  - name: visualization
    tags: ['core']
    panes:
      - ros2 launch walker_step_detector plot_steps.launch.py      
      - ros2 run walker_plot plot_forces      # should add params and launch file ...
      - ros2 run walker_loads plot_loads      # should add params and launch file ... squaternion python3-matplotlib
  - name: record
    tags: ['record']
    panes:
      - ros2 launch walker_bringup bag_recorder.launch.py --topic_list  /left_handle /left_wheel /odom /odom_lscm /right_handle /right_wheel /scan_filtered /sensor/bwt901cl/Angle /sensor/bwt901cl/Imu /sensor/bwt901cl/MagneticField /sensor/bwt901cl/Temperature /tf /tf_static /detected_step_left /detected_step_right /left_loads /right_loads /user_desc /points2

