session: walker_ros2
init_cmd: |
  # Any config variable goes here.
  source ~/.walker_cfg.bash
  # This configures scripts to work and sources workspace
  source $ROS2_WORKSPACE/src/WalKit/walker_bringup/script/walker_config.bash
windows:
  - name: arduino
    tags: ['core']
    panes:
      - ros2 launch walker_arduino left_handle.launch.py
      - ros2 launch walker_arduino right_handle.launch.py
      - ros2 launch walker_arduino left_wheel.launch.py
      - ros2 launch walker_arduino right_wheel.launch.py
  - name: sensors1
    tags: ['core']
    panes:
      - ros2 launch rplidar_ros2  rplidar_launch.py inverted:=true
      - ros2 run bwt901cl_pkg imu_bwt901cl      
      - ros2 launch walker_diff_odom walker_diff_odom.launch.py
  - name: sensors2
    tags: ['core']
    panes:
      - ros2 launch walker_bringup laser_filter.launch.py
      - ros2 launch ros2_laser_scan_matcher demo_lsm.launch.py
  - name: walker_description
    tags: ['core']
    panes:
    # walker physical dimensions are in xacro AND  params.yaml files
      - ros2 launch walker_description walker_state_publisher.launch.py
      - ros2 run walker_description handle_tf_publisher.py
  - name: web
    tags: ['core']
    panes:
      - ros2 run walker_bringup record_service.py
      - ros2 launch rosbridge_server rosbridge_websocket_launch.xml
      - cd ~/workspace/walker_ws/src/WalKit/walker_web_gui/gui; python3 -m http.server 8080
  - name: gait_analysis
    tags: ['core']
    panes:
      - ros2 launch walker_step_detector step_detector_km.launch.py
      - ros2 launch walker_loads partial_loads.launch.py
      - ros2 launch walker_centroid_support centroid_support.launch.py
  - name: visualization
    tags: ['core']
    panes:
      - ros2 launch walker_step_detector plot_steps.launch.py      
      - ros2 run walker_plot plot_forces         # should add params and launch file ...
      - ros2 run walker_loads plot_loads.py      # should add params and launch file ...
  - name: record
    tags: ['record']
    panes:
      - ros2 launch walker_bringup bag_recorder.launch.py

