# This first line must be the node name!
/step_laser_filter:
  ros__parameters:
    use_sim_time: False
    filter:
      in_topic: /scan_filtered
      out_topic: /scan_feet
      name: inverted_box_filter
      type: laser_filters/LaserScanBoxFilter
      remove_out: True
      params:
        box_frame: laser
        max_x: 0.03
        max_y: 0.3
        max_z: 1.0
        min_x: -1.2
        min_y: -0.3
        min_z: -1.0